services:
  argo-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro   # Map the config.yaml file into the container